function sayBye()
    % Print a goodbye message to the console
    msg = [
    '\nAll done',...
    '\n',...
    '\n   |\\      _,,,---,,_      ',...
    '\n   /,`.-''`''    -.  ;-;;,_  ',...
    '\n  |,4-  ) )-,_. ,\\ (  `''-'' ',...
    '\n ''---''''(_/--''  `-''\\_)      ',...
    '\n\n'
    ];
    fprintf(msg);
end
