clear matlabbatch;
matlabbatch{1}.spm.tools.oldnorm.est.subj = struct('source', {}, 'wtsrc', {});
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.template = '<UNDEFINED>';
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.weight = '';
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.smosrc = 8;
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.smoref = 0;
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.regtype = 'mni';
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.cutoff = 25;
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.nits = 0;
matlabbatch{1}.spm.tools.oldnorm.est.eoptions.reg = Inf;
spm_jobman('run', matlabbatch);
